echo [1/3] Installing dependencies...
pip install fastapi uvicorn sqlalchemy psycopg2-binary pydantic google-generativeai faiss-cpu numpy python-multipart python-dotenv requests
echo [2/3] Seeding 25 employees (skips if exists)...
python seed_data.py
echo [3/3] Starting backend server on Port 8000...
uvicorn main:app --host 127.0.0.1 --port 8000 --reload
pause
