import { Ticket, StatsData } from './types';

export const MOCK_STATS: StatsData = {
  openTickets: 124,
  avgResolution: '2.4h',
  customerCsat: 98,
  systemHealth: 'Active',
};

export const MOCK_TICKETS: Ticket[] = [
  {
    id: '1',
    ticketNumber: '#4492',
    subject: 'VPN Connection dropping on M1 MacOS',
    description: 'The VPN keeps disconnecting every 20 minutes on M1 MacBook Pro. Already tried clearing system cache and reinstalling the VPN client. Issue persists across all network environments.',
    requester: {
      id: 'r1',
      name: 'Elena Vance',
      department: 'Engineering',
    },
    agent: {
      id: 'a1',
      name: 'Marcus Thorne',
    },
    status: 'critical',
    priority: 'urgent',
    category: 'Network',
    lastMessage: '"I\'ve tried clearing the system cache but..."',
    createdAt: new Date(Date.now() - 2 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
  },
  {
    id: '2',
    ticketNumber: '#4489',
    subject: 'Access request for Adobe Creative Cloud',
    description: 'New user needs access to Adobe Creative Cloud suite for their onboarding. Requires all design-related applications.',
    requester: {
      id: 'r2',
      name: 'Julian Rossi',
      department: 'Marketing',
    },
    agent: null,
    status: 'pending',
    priority: 'medium',
    category: 'Licensing',
    lastMessage: 'New user onboarding requirements.',
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: '3',
    ticketNumber: '#4485',
    subject: 'Encrypted drive recovery after lockout',
    description: 'Employee locked out of encrypted drive after forgetting the recovery passphrase. Legal department data access is critical.',
    requester: {
      id: 'r3',
      name: 'Sarah Jenkins',
      department: 'Legal',
    },
    agent: {
      id: 'a1',
      name: 'Marcus Thorne',
    },
    status: 'in_progress',
    priority: 'high',
    category: 'Hardware',
    lastMessage: '"Sent the recovery key via secure channel."',
    createdAt: new Date(Date.now() - 4 * 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60000).toISOString(),
  },
  {
    id: '4',
    ticketNumber: '#4480',
    subject: 'Slack notifications not working on Windows',
    description: 'Desktop notifications from Slack stopped appearing after a recent Windows update. Sound alerts still work.',
    requester: {
      id: 'r4',
      name: 'David Kim',
      department: 'Product',
    },
    agent: {
      id: 'a2',
      name: 'Priya Patel',
    },
    status: 'resolved',
    priority: 'low',
    category: 'Software',
    lastMessage: 'Issue resolved after registry fix applied.',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60000).toISOString(),
  },
  {
    id: '5',
    ticketNumber: '#4478',
    subject: 'Printer offline in Finance floor',
    description: 'The HP LaserJet Pro on floor 3 shows offline status despite being powered on. Multiple employees affected.',
    requester: {
      id: 'r5',
      name: 'Amanda Torres',
      department: 'Finance',
    },
    agent: {
      id: 'a3',
      name: 'Tom Bradley',
    },
    status: 'faq_resolved',
    priority: 'medium',
    category: 'Hardware',
    lastMessage: 'Resolved via FAQ knowledge base article K-1024.',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60000).toISOString(),
  },
  {
    id: '6',
    ticketNumber: '#4475',
    subject: 'Multi-factor authentication not sending SMS',
    description: 'MFA SMS codes are not being sent to the registered mobile number. Employee cannot log into corporate systems.',
    requester: {
      id: 'r6',
      name: 'Robert Chen',
      department: 'Sales',
    },
    agent: {
      id: 'a1',
      name: 'Marcus Thorne',
    },
    status: 'action_path_resolved',
    priority: 'high',
    category: 'Security',
    lastMessage: 'Authentication method switched to authenticator app.',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60000).toISOString(),
  },
  {
    id: '7',
    ticketNumber: '#4470',
    subject: 'Legacy system data migration failure',
    description: 'Critical data migration from the legacy ERP system fails at 67% every time. Data integrity needs to be verified.',
    requester: {
      id: 'r7',
      name: 'Lisa Morgan',
      department: 'Operations',
    },
    agent: {
      id: 'a2',
      name: 'Priya Patel',
    },
    status: 'complex_path_resolved',
    priority: 'urgent',
    category: 'Software',
    lastMessage: 'Complex migration path executed with data integrity checks passed.',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60000).toISOString(),
  },
];
